spring:
  application:
    name: authorization-app
    version: @project.version@
    artifactId: @project.artifactId@
  profiles:
    active: local
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
